---
- name: Check Python Version
  hosts: "{{ DEPLOYSERVERS }}"
  gather_facts: false
  become: true
  vars:
    python_version: 3.5.0
    ansible_python_interpreter: /usr/bin/python
  tasks:
    # python_version is a given variable, eg. `3.5`
    - name: Check if python is already latest
      # Если использовать python2 то значение возвращаеться в stderr, если python2 то в stdout
      shell: /usr/bin/python3 --version
      register: python_version_result
      failed_when: python_version_result.stdout | replace('Python ', '') is version(python_version, '>=')

    - debug:
        var: python_version_result.stdout

#- name: Install prerequisites
#  apt: name=python-software-properties state=present
#  become: true

#- name: Add deadsnakes repo
#  apt_repository: repo="ppa:deadsnakes/ppa"
#  become: true

#- name: Install python
#  apt: name="python{{ python_version }}-dev" state=present
#  become: true