---
- name: Install Puppet 6 Agent
  hosts: "{{ DEPLOYSERVERS }}"
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - import_role:
        name: puppet_standalone
