---
- name: Install Shell Tools
  hosts: "{{ DEPLOYSERVERS }}"
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - import_role:
        name: set_timezone