- name: Install the puppet rpm from a remote repo (Centos)
  yum:
    name: https://yum.puppet.com/puppet6-release-el-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
    #when: ansible_distribution_major_version == '7'

- name: Set puppet6.repo's puppet6 section enabled to 1
  ini_file:
    path: /etc/yum.repos.d/puppet6.repo
    section: puppet6
    option: enabled
    value: 1
    create: no
    backup: no


#- name: Run the equivalent of "yum update"
#  yum:
#    update_cache: yes